# Generated by Django 4.1.13 on 2024-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trainName",
                    models.CharField(default="Prayagraj Express", max_length=100),
                ),
                ("trainNumber", models.CharField(max_length=255, unique=True)),
                (
                    "source",
                    models.CharField(default="Ahmedabad Junction", max_length=100),
                ),
                (
                    "destination",
                    models.CharField(default="Allahabad Junction", max_length=100),
                ),
                ("departureTime", models.TimeField(default="00:00")),
                ("arrivalTime", models.TimeField(default="00:00")),
                ("travelDuration", models.CharField(default="18h 55m", max_length=10)),
                (
                    "fare",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
                ("availableSeats", models.IntegerField(default=120)),
                ("trainType", models.CharField(default="Express", max_length=50)),
                ("daysOfOperation", models.JSONField(default=list)),
                ("coaches", models.JSONField(default=list)),
            ],
        ),
    ]
