# Generated by Django 4.1.13 on 2024-09-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.hotel"
            ),
        ),
    ]
