# Generated by Django 4.1.13 on 2024-09-16 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_alter_room_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="hotel",
        ),
    ]
