# Generated by Django 4.1.13 on 2024-09-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_remove_room_hotel"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotels.hotel",
            ),
        ),
    ]
